##############################################################
# Learning Series: Network Programmability Basics
# Module: NetDevOps
# Lesson: Ansible Part 1: What you need to Get Started
# Author: Hank Preston <hapresto@cisco.com>
# 
# example1.yaml
# Illustrate the following concepts:
# - Basic Playbook Structure
# - Use of Variables
##############################################################
---
- name: Report Hostname and Operating System Details
  hosts: servers
  
  tasks: 
    - name: "Get hostname from server"
      debug: 
        msg: "{{ansible_hostname}}"
    
    - name: "Operating System"
      debug: msg="{{ansible_distribution}}"
      
- name: Report Network Details of Servers
  hosts: servers
  become: yes
  
  tasks: 
    - name: "Default IPv4 Interface"
      debug: msg="{{ansible_default_ipv4.interface}}"
      
    - name: "Retrieve network routes"
      command: "ip route list"
      register: routes
      
    - name: "Network routes installed"
      debug: msg="{{routes}}"
            