##############################################################
# Learning Series: Network Programmability Basics
# Module: NetDevOps
# Lesson: Ansible Part 1: What you need to Get Started
# Author: Hank Preston <hapresto@cisco.com>
# 
# example3.yaml
# Illustrate the following concepts:
# - Using Jinja templates
##############################################################
---
- name: Generate Configuration from Template
  hosts: localhost
  gather_facts: false
  vars: 
    feature: bgp
    asn: 65001
    router_id: 10.10.10.1
    
  tasks: 
    - name: "Generate config"
      template: 
        src: "example3.j2"
        dest: "./example3.conf"

