##############################################################
# Learning Series: Network Programmability Basics
# Module: NetDevOps
# Lesson: Ansible Part 2: Using Ansible for Network Configuration
# Author: Hank Preston <hapresto@cisco.com>
#
# Illustrate the following concepts:
# -
##############################################################
---
- name: Enable Model Driven Programmability (NETCONF) on IOS-XE
  hosts: iosxe
  connection: local
  gather_facts: false

  roles:
    - iosxe_mdp

- name: Enable NX-API on NX-OS
  hosts: nxos
  connection: local
  gather_facts: false

  roles:
    - nxos_nxapi

- name: Configure Network Core
  hosts: core
  connection: local
  gather_facts: false

  roles:
    - netconf_l3_interfaces
    - netconf_ospf

- name: Configure Distribution Switches
  hosts: distribution
  connection: local
  gather_facts: false

  roles:
    - nxos_vlans
    - nxos_vpc
    - nxos_vpc_trunks
    - nxos_l3_interfaces
    - nxos_hsrp
    - nxos_ospf

- name: Configure Access Switches
  hosts: access
  connection: local
  gather_facts: false

  roles:
    - nxos_vlans
    - nxos_l3_interfaces
    - nxos_po_trunks
