l3_fabric: 
    interfaces: 
        - name: Ethernet1/1
          desc: L3 Link to nx-osv9000-1
          ip_address: 172.20.0.6
          prefix: 30
        - name: Ethernet1/2
          desc: L3 Link to nx-osv9000-2
          ip_address: 172.20.0.14
          prefix: 30
local_loopbacks:
    - name: Loopback11
      desc: Sample Network Route Injection
      ip_address: 172.24.1.1
      prefix: 24          
    - name: Loopback12
      desc: Sample Network Route Injection
      ip_address: 172.24.2.1
      prefix: 24          
    - name: Loopback13
      desc: Sample Network Route Injection
      ip_address: 172.24.3.1
      prefix: 24          
    - name: Loopback14
      desc: Sample Network Route Injection
      ip_address: 172.24.4.1
      prefix: 24
bgp: 
    asn: 65534
    router_id: 192.168.0.4
    neighbors: 
        - neighbor: 172.20.0.5
          asn: 65531
          description: nx-osv9000-1
          update_source: Ethernet1/1
        - neighbor: 172.20.0.13
          asn: 65532
          description: nx-osv9000-2
          update_source: Ethernet1/2
    networks:
        - - 172.24.1.0/24
        - - 172.24.2.0/24
        - - 172.24.3.0/24
        - - 172.24.4.0/24
      