##############################################################
# Learning Series: Network Programmability Basics
# Module: NetDevOps
# Lesson: Application Centric Infrastructure and Ansible
# Author: Hank Preston <hapresto@cisco.com>
#
# Illustrate the following concepts:
# - Managing Application Policy with Ansible
# - aci_ap module
# - aci_epg module
##############################################################
---
- name: Example 2 - Managing Application Profiles and EPGs
  hosts: apic
  connection: local
  gather_facts: False
  vars_prompt:
    - name: "prefix"
      prompt: "What are your initials?"
      private: no
  vars:
    tenant: "{{ prefix }}_Tenant2"
    ap: "Supply_Chain"
    epgs:
      - epg: "web"
      - epg: "sql"

  tasks:
    - name: Create Application Profile
      aci_ap:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "present"
        validate_certs: False
        tenant: "{{ tenant }}"
        ap: "{{ ap }}"
        descr: "App Profile Created Using Ansible"

    - name: Create EPGs
      aci_epg:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "present"
        validate_certs: False
        tenant: "{{ tenant }}"
        ap: "{{ ap }}"
        epg: "{{ item.epg }}"
        description: "EPG Created Using Ansible"
      with_items: "{{ epgs }}"
