##############################################################
# Learning Series: Network Programmability Basics
# Module: NetDevOps
# Lesson: Ansible Part 3: Your Network as Code
# Author: Hank Preston <hapresto@cisco.com>
#
# Illustrate the following concepts:
# -
##############################################################
---
- name: Enable Features
  tags: [api, nxapi, layer3]
  loop:
    - interface-vlan
  nxos_feature:
    feature: "{{ item }}"
    state: enabled

- name: Configure Layer 3 Interfaces
  tags: [api, nxapi, layer3]
  loop: "{{ l3_interfaces }}"
  nxos_interface:
    interface: "{{ item.interface_type }}{{ item.interface_id }}"
    mode: layer3
    description: "{{ item.description }}"
    admin_state: up

- name: Configure IPv4 Address on Interface
  tags: [api, nxapi, layer3]
  loop: "{{ l3_interfaces }}"
  nxos_ip_interface:
    interface: "{{ item.interface_type }}{{ item.interface_id }}"
    version: v4
    addr: "{{ item.ip_address }}"
    mask: "{{ item.prefix }}"
